### ISSUE TITLE
Crash on opening Fabricator

### ISSUE THREAD

**Issue by BillboardEric** [xy-project/Project-XY#1]
http://hastebin.com/arojobixot.1c

**Comment by xy-project** [comment]
Aparrently with Forge, nested dependencies don't work. Will be fixed in next release.

**Comment by xy-project** [comment]
https://github.com/Chicken-Bones/CodeChickenLib/commit/05bd26eb87d873cad66abf762299c05633cc56b4 ChickenBones moved it. You have an old version of CCLib somehow. Update your modpack. Or your version of CodeChickenCore, and delete the CCLib in the /mods/1.7.10 folder
