### ISSUE TITLE
Server Calls a Render Method Revisited

### ISSUE THREAD

**Issue by Ommina** [xy-project/Project-XY#16]
If I'm able to re-open #3, I can't figure out how.  

http://pastebin.com/PyfSBAtn

**Project-XY 1.7.10-0.2.0-pre** and **extrautilities-1.2.11.jar**.

Paste won't even expire this time.

**Comment by xy-project** [comment]
Thanks for the log. I'll take a look at it when I have time.

**Comment by BuckTheWeasel** [comment]
has this been fixed ? i can't play on server if so were can i download it.

**Comment by xy-project** [comment]
This is fixed and will be released in a future version for 1.7.10

**Comment by Roadhog360** [comment]
Was the fix ever released?
