### ISSUE TITLE
In Multi-Tanks can't be used Custom Xychoridite Blocks

### ISSUE THREAD

**Issue by nikita488** [xy-project/Project-XY#8]
In Multi-Tanks can't be used Custom Xychoridite Blocks
![2015-08-24_20 30 05](https://cloud.githubusercontent.com/assets/6237881/9447272/2484d8da-4a9f-11e5-83af-2af164389e6a.png)

**Comment by xy-project** [comment]
Yep, custom xychoridite blocks won't work. I'm actually thinking about merging the standard ones into the customs. It would be much easier to keep connected textures.
